### ISSUE TITLE
sigmund external for windows?

### ISSUE THREAD

**Issue by simonvanderveldt** [monome-community/plane#1]
Hi @tehn , Any chance you can publish the sigmund external for Windows as well?
If I understand it correctly the `mxo` file is macOS specific, the Windows one would have the extension `mxe`.

**Comment by tehn** [comment]
ted apel made sigmund~ and it seems only available for mac.

http://vud.org/max/

he has the source on his github but it's also mac only:

https://github.com/v7b1/sigmund_64bit-version

**Comment by simonvanderveldt** [comment]
OK, thanks for the info!
